name: windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
       sudo apt update
       sudo apt install aria2 tree unzip
       aria2c https://github.com/liaoke01/uupd/blob/main/1.zip
    - name: finish
      run: |
       unzip 1.zip
       tree
       cd ./1
       ./uup_download_linux.sh
