name: windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up 
      run: |
       sudo apt update
       sudo apt install aria2 tree unzip


    - name: Checkout
      uses: actions/checkout@main
            
    - name: finish
      run: |
       cd ./1
       chmod 777 uup_download_linux.sh
       sudo sh uup_download_linux.sh
